apiVersion: apps/v1
kind: Deployment
metadata:
  name: hape-dora-demo-service-u
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hape-dora-demo-service-u
  template:
    metadata:
      labels:
        app: hape-dora-demo-service-u
    spec:
      containers:
      - name: hape-dora-demo-service-u
        image: nginx:1.27
        ports:
        - containerPort: 80
